name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

env:
  fail-fast: true

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
        dbal-version:
          - "^2.12"
          - "^3.0"
        dependencies:
          - "highest"
          - "lowest"
        optional_dependencies:
          - true
          - false

    services:
      mysql:
        image: "mysql:5.7"

        options: >-
          --health-cmd "mysqladmin ping --silent"
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=database

        ports:
          - "3306:3306"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          extensions: "pdo_mysql"

      - name: "Install desired DBAL version"
        run: "composer require doctrine/dbal ${{ matrix.dbal-version }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        if: "! startsWith(matrix.php-version, '8')"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-suggest"

      - name: "Install dependencies with Composer (--ignore-platform-req=php)"
        uses: "ramsey/composer-install@v1"
        if: "startsWith(matrix.php-version, '8')"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-suggest --ignore-platform-req=php"

      - name: "Remove optional dependencies"
        if: "! startsWith(matrix.php-version, '8') && ! matrix.optional_dependencies"
        run: "composer remove --dev doctrine/data-fixtures doctrine/migrations"

      - name: "Remove optional dependencies (--ignore-platform-req=php)"
        if: "startsWith(matrix.php-version, '8') && ! matrix.optional_dependencies"
        run: "composer remove --ignore-platform-req=php --dev doctrine/data-fixtures doctrine/migrations"

      - name: "Configure test application"
        run: "cp ci/config/application.config.php config/application.config.php"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

      - name: "Test coverage"
        run: "php build/coverage-checker.php coverage.xml 70"

      - name: "Run CLI commands"
        run: "./ci/run-cli.sh"

      - name: "Run migration CLI commands"
        if: "${{ matrix.optional_dependencies }}"
        run: "./ci/run-cli-migrations.sh"

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v2"
        with:
          name: "phpunit-${{ matrix.php-version }}.coverage"
          path: "coverage.xml"

  upload_coverage:
    name: "Upload coverage to Codecov"
    runs-on: "ubuntu-20.04"
    needs:
      - "phpunit"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Download coverage files"
        uses: "actions/download-artifact@v2"
        with:
          path: "reports"

      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v1"
        with:
          directory: "reports"
